### ISSUE TITLE
Check that there is no text after the metadata

### ISSUE THREAD

**Issue by addaleax** [evanlucas/core-validate-commit#6]
It would be cool to check whether there is some text after the metadata block, because that sometimes happens unintentionally when squashing commits together, e.g. in my https://github.com/nodejs/node/commit/c5545f2c63fe30b0cfcdafab18c26df8286881d0.

(I may find the time to look into this myself, but just in case I don’t, I want to have mentioned it)

**Comment by evanlucas** [comment]
I like it. I'll go ahead and work on this. On another note, [git-fixit](https://github.com/evanlucas/git-fixit) is what I use for daily squashing (although it uses fixup instead of squash so the commit messages aren't melded into the previous)

**Comment by evanlucas** [comment]
Just published `core-validate-commit@2.2.0`. The rule will be disabled if `--no-validate-metadata` flag is passed to core-validate-commit, otherwise, it will be enabled. Thanks!

**Comment by addaleax** [comment]
Wow, that was fast! Thanks, it works! :tada:
